In [111]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
import csv
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestRegressor
import joblib

In [112]:
# 学習データの読み込み
# 学習データの読み込み
train_df=pd.read_csv("/Users/tasuke0630/making/DataScience/Score_prediction/data.csv")
train_df.head()

,Unnamed: 0,Opponent,Date,Position,Mins,Goals,Assists,Shots,keyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,0,Valencia (A)2 - 3,02-05-2021,FW,90,2\t,-\t,5,1\t,7\t,3\t,-\t,2\t,2\t,9.18
1,1,Granada (H)1 - 2,29-04-2021,FW,90,1\t,-\t,6,2\t,3\t,6\t,-\t,2\t,3\t,7.83
2,2,Villarreal (A)1 - 2,25-04-2021,FW,90,-\t,-\t,3,-\t,2\t,6\t,-\t,4\t,2\t,6.78
3,3,Getafe (H)5 - 2,22-04-2021,FW,90,2\t,1\t,7,1\t,2\t,4\t,-\t,1\t,1\t,10.00
4,4,Real Madrid (A)2 - 1,10-04-2021,AMC,90,-\t,-\t,7,2\t,7\t,3\t,-\t,6\t,1\t,7.84

In [113]:
# 元データをコピー
df=train_df.copy()
df=df.rename(columns={df.columns[0] :"a"})

#使わないカラムを削除する
df2=df.drop(columns=["a","Opponent","Date"])
df2.head()

,Position,Mins,Goals,Assists,Shots,keyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,FW,90,2\t,-\t,5,1\t,7\t,3\t,-\t,2\t,2\t,9.18
1,FW,90,1\t,-\t,6,2\t,3\t,6\t,-\t,2\t,3\t,7.83
2,FW,90,-\t,-\t,3,-\t,2\t,6\t,-\t,4\t,2\t,6.78
3,FW,90,2\t,1\t,7,1\t,2\t,4\t,-\t,1\t,1\t,10.00
4,AMC,90,-\t,-\t,7,2\t,7\t,3\t,-\t,6\t,1\t,7.84

In [114]:
list_1=[]
list_2=[]
list_3=[]
list_4=[]
list_5=[]
list_6=[]
list_7=[]
list_8=[]
tmp=[]

df3=df2.drop(columns=["Goals","Assists","keyP","Drb","Fouled","Off","Disp","UnsTch"])

warnings.simplefilter("ignore")

list_1=df2.loc[:,"Goals"]
for i in range(len(list_1)):
    tmp=list_1[i]
    list_1[i]=tmp.replace("\t","")
for i in range(len(list_1)):
    tmp=list_1[i]
    list_1[i]=tmp.replace("-","0")  
    
    
list_2=df2.loc[:,"Assists"]
for i in range(len(list_2)):
    tmp=list_2[i]
    list_2[i]=tmp.replace("\t","")
for i in range(len(list_2)):
    tmp=list_2[i]
    list_2[i]=tmp.replace("-","0")
    
    
list_3=df2.loc[:,"keyP"]
for i in range(len(list_3)):
    tmp=list_3[i]
    list_3[i]=tmp.replace("\t","")
for i in range(len(list_3)):
    tmp=list_3[i]
    list_3[i]=tmp.replace("-","0")
    
    
list_4=df2.loc[:,"Drb"]
for i in range(len(list_4)):
    tmp=list_4[i]
    list_4[i]=tmp.replace("\t","")
for i in range(len(list_4)):
    tmp=list_4[i]
    list_4[i]=tmp.replace("-","0")
    
    
list_5=df2.loc[:,"Fouled"]
for i in range(len(list_5)):
    tmp=list_5[i]
    list_5[i]=tmp.replace("\t","")
for i in range(len(list_5)):
    tmp=list_5[i]
    list_5[i]=tmp.replace("-","0")
    
    
list_6=df2.loc[:,"Off"]
for i in range(len(list_6)):
    tmp=list_6[i]
    list_6[i]=tmp.replace("\t","")
for i in range(len(list_6)):
    tmp=list_6[i]
    list_6[i]=tmp.replace("-","0")
    
    
list_7=df2.loc[:,"Disp"]
for i in range(len(list_7)):
    tmp=list_7[i]
    list_7[i]=tmp.replace("\t","")
for i in range(len(list_7)):
    tmp=list_7[i]
    list_7[i]=tmp.replace("-","0")
    
    
list_8=df2.loc[:,"UnsTch"]
for i in range(len(list_8)):
    tmp=list_8[i]
    list_8[i]=tmp.replace("\t","")
for i in range(len(list_8)):
    tmp=list_8[i]
    list_8[i]=tmp.replace("-","0")

In [115]:
x1=pd.DataFrame(list_1)
x2=pd.DataFrame(list_2)
x3=pd.DataFrame(list_3)
x4=pd.DataFrame(list_4)
x5=pd.DataFrame(list_5)
x6=pd.DataFrame(list_6)
x7=pd.DataFrame(list_7)
x8=pd.DataFrame(list_8)

In [116]:
train=pd.concat([df3,x1,x2,x3,x4,x5,x6,x7,x8],axis=1)
train

   Position  Mins  Shots  Rating Goals Assists keyP Drb Fouled Off Disp UnsTch
0        FW    90      5    9.18     2       0    1   7      3   0    2      2
1        FW    90      6    7.83     1       0    2   3      6   0    2      3
2        FW    90      3    6.78     0       0    0   2      6   0    4      2
3        FW    90      7   10.00     2       1    1   2      4   0    1      1
4       AMC    90      7    7.84     0       0    2   7      3   0    6      1
5       AMC    90      7    7.29     0       0    5   2      2   0    7      2
6       AMC    90      5    9.54     2       1    2   3      1   0    7      1
7       AMC    90      6   10.00     2       1    3   5      4   0    5      1
8        FW    90      5    8.77     0       2    6   5      0   1    2      4
9        FW    90      4    9.49     1       1    1   7      4   0    2      1
10       FW    90      3    9.11     2       0    1   4      1   0    2      2
11       FW    90      8    7.61     1       0    2   3      0   0    1      3
12       FW    90      7   10.00     2       1    2   1      3   0    2      1
13      Sub    33      2    8.06     1       0    2   3      2   0    0      1
14       FW    90      4    9.70     1       0    4  11      5   0    2      1
15       FW    65      2    8.97     2       0    0   0      2   0    0      1
16       FW    90      5    9.15     2       0    1   5      2   2    2      2
17      AMR    90      8    8.29     0       1    1   6      3   1    2      0
18      AMC    90     11   10.00     1       1    3   5      0   0    2      1
19       FW    90     10    8.43     1       0    3   6      3   0    2      2
20       FW    90      3    7.72     0       0    2   4      3   0    1      3
21       FW    90     12    9.17     1       0    3   2      4   0    4      1
22      AMR    90     10    8.63     0       0    2   9      3   0    2      3
23      AMR    90      5    9.10     1       0    4   3      2   0    1      1
24      AMC    90      3    7.38     0       0    3   4      3   0    2      1
25      Sub    45      3    8.31     2       0    2   1      1   0    0      0
26      AMC    90     10    9.11     0       0    4  12      3   1    3      5
27       FW    90      3    6.57     0       0    1   3      2   0    6      3
28      AMR    90      3    7.42     0       0    1   4      3   0    2      1
29       FW    90      3    7.05     0       0    2   3      1   0    2      0
30       FW    90      2    7.22     0       0    2   2      5   1    3      3
31       FW    90      7    8.51     1       0    1   2      2   0    1      1

In [117]:
#カテゴリカル変数の数値変換
tmp_Position=pd.get_dummies(train["Position"],prefix="Position")
train=pd.concat([train,tmp_Position],axis=1).drop(columns="Position")
train

,Mins,Shots,Rating,Goals,Assists,keyP,Drb,Fouled,Off,Disp,UnsTch,Position_AMC,Position_AMR,Position_FW,Position_Sub
0,90,5,9.18,2,0,1,7,3,0,2,2,0,0,1,0
1,90,6,7.83,1,0,2,3,6,0,2,3,0,0,1,0
2,90,3,6.78,0,0,0,2,6,0,4,2,0,0,1,0
3,90,7,10.00,2,1,1,2,4,0,1,1,0,0,1,0
4,90,7,7.84,0,0,2,7,3,0,6,1,1,0,0,0
5,90,7,7.29,0,0,5,2,2,0,7,2,1,0,0,0
6,90,5,9.54,2,1,2,3,1,0,7,1,1,0,0,0
7,90,6,10.00,2,1,3,5,4,0,5,1,1,0,0,0
8,90,5,8.77,0,2,6,5,0,1,2,4,0,0,1,0
9,90,4,9.49,1,1,1,7,4,0,2,1,0,0,1,0
10,90,3,9.11,2,0,1,4,1,0,2,2,0,0,1,0
11,90,8,7.61,1,0,2,3,0,0,1,3,0,0,1,0
12,90,7,10.00,2,1,2,1,3,0,2,1,0,0,1,0
13,33,2,8.06,1,0,2,3,2,0,0,1,0,0,0,1
14,90,4,9.70,1,0,4,11,5,0,2,1,0,0,1,0
15,65,2,8.97,2,0,0,0,2,0,0,1,0,0,1,0
16,90,5,9.15,2,0,1,5,2,2,2,2,0,0,1,0
17,90,8,8.29,0,1,1,6,3,1,2,0,0,1,0,0
18,90,11,10.00,1,1,3,5,0,0,2,1,1,0,0,0
19,90,10,8.43,1,0,3,6,3,0,2,2,0,0,1,0
20,90,3,7.72,0,0,2,4,3,0,1,3,0,0,1,0
21,90,12,9.17,1,0,3,2,4,0,4,1,0,0,1,0
22,90,10,8.63,0,0,2,9,3,0,2,3,0,1,0,0
23,90,5,9.10,1,0,4,3,2,0,1,1,0,1,0,0
24,90,3,7.38,0,0,3,4,3,0,2,1,1,0,0,0
25,45,3,8.31,2,0,2,1,1,0,0,0,0,0,0,1
26,90,10,9.11,0,0,4,12,3,1,3,5,1,0,0,0
27,90,3,6.57,0,0,1,3,2,0,6,3,0,0,1,0
28,90,3,7.42,0,0,1,4,3,0,2,1,0,1,0,0
29,90,3,7.05,0,0,2,3,1,0,2,0,0,0,1,0
30,90,2,7.22,0,0,2,2,5,1,3,3,0,0,1,0
31,90,7,8.51,1,0,1,2,2,0,1,1,0,0,1,0

In [118]:
#trainのデータ
train_x=train.drop(columns=["Goals"])
train_y=train["Goals"]

In [119]:
clf=RandomForestRegressor(n_jobs=-1, random_state=1400)
clf.fit(train_x,train_y)

RandomForestRegressor(n_jobs=-1, random_state=1400)

In [134]:
# 相関行列を計算
coef=np.corrcoef(train.loc[:,"Drb"], train.loc[:,"Goals"])

# 相関行列を表示
print(coef)

TypeError: unsupported operand type(s) for /: 'str' and 'int'