In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
import csv
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestRegressor
import joblib

In [3]:
df=pd.read_csv("/Users/tasuke0630/making/DataScience/Score_prediction/graph_material.csv")
train_df=df.copy()
train_df=train_df.rename(columns={df.columns[0] :"a"})

#使わないカラムを削除する
df2=train_df.drop(columns=["a"])
df2.head()

,Mins,Shots,Rating,Goals,Assists,keyP,Drb,Fouled,Off,Disp,UnsTch,Position_AMC,Position_AMR,Position_FW,Position_Sub
0,90,5,9.18,2,0,1,7,3,0,2,2,0,0,1,0
1,90,6,7.83,1,0,2,3,6,0,2,3,0,0,1,0
2,90,3,6.78,0,0,0,2,6,0,4,2,0,0,1,0
3,90,7,10.00,2,1,1,2,4,0,1,1,0,0,1,0
4,90,7,7.84,0,0,2,7,3,0,6,1,1,0,0,0

In [5]:
#trainのデータ
train_x=df2.drop(columns=["Goals"])
train_y=df2["Goals"]

In [6]:
clf=RandomForestRegressor(n_jobs=-1, random_state=1400)
clf.fit(train_x,train_y)

RandomForestRegressor(n_jobs=-1, random_state=1400)

In [51]:
#特徴量の重要度
feature=clf.feature_importances_

#特徴量の重要度を上から順に出力する
x1=pd.DataFrame({"number": range(len(feature)),"feature": feature[:]})
x2=x1.sort_values("feature",ascending=False).reset_index()

#特徴量の高い順（列の要素を表す）
x3=x2.loc[:,"number"]

In [63]:
#特徴量の名前
label=train_x.columns[0:]

#特徴量の高い順（名前順）
x4=x2

warnings.simplefilter("ignore")

for i in range(len(label)):
    x4["number"][i]=label[x3[i]]
    
x4=x4.drop(columns="index")
x4.rename(columns={x4.columns[0] :"name"})

            name   feature
0         Rating  0.577416
1         UnsTch  0.080853
2            Drb  0.073969
3           keyP  0.070658
4          Shots  0.062304
5           Disp  0.054450
6         Fouled  0.034058
7            Off  0.013861
8    Position_FW  0.013807
9   Position_Sub  0.007556
10  Position_AMR  0.003764
11          Mins  0.002643
12  Position_AMC  0.002611
13       Assists  0.002049